#Dean Woelfle
#12/16/2020
#Lab 4
#Project Euler Problems

#Lets the user select a problem
Problem = input("Type a number to choose a problem. Possible problems: 1 - 6 \n")
print("")

#problem 1
if (Problem == '1'):

    #reads prompt of problem
    print("Find the sum of all the multiples of 3 or 5 below 1000.\n")
    #total
    sum = 0
    #runs through every number from 1 to 1000
    for num in range(1, 1000):

        #sees if it is divisible by 3
        if (num % 3 == 0):
            #if so, adds it to total
            sum += num 
        #sees if it is divisible by 3
        elif (num % 5 == 0):
            #if so, adds it to total
            sum += num 
    #turns total into a string
    sum = str(sum)
    #prints out answer (total)
    print("The sum of all the multiples of 3 or 5 below 1000 is " + sum)

#problem 2
elif (Problem == '2'):

    #reads prompt of problem
    print("Each new term in the Fibonacci sequence is generated by adding the previous two terms.\nBy considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.\n")
    #List for Fibonacci sequence
    FibList = [1,2]
    #total
    sum = 0
    #makes sure sequence doesn't go above four million
    while ((FibList[-1]+FibList[-2]) < 4000000):
        #adds most recent to second most recent value in sequence to get newest value
        FibList.append(FibList[-1]+FibList[-2])

    #runs through all values in sequence and sees if they are divisible by 2 (even)
    for num in FibList:
        if (num % 2 == 0):
            #if so, adds it to total
            sum += num
    #turns total into a string
    sum = str(sum)
    #prints out answer (total)
    print("The sum of all the even valued terms less than four million in the Fibonacci sequence is " + sum)

#problem 3
elif (Problem == '3'):

    #reads prompt of problem
    print("What is the largest prime factor of the number 600851475143?")

    #list for calculated prime factors
    primes = []

    #goes through a list of numbers (the reason I chose 10,000 as a max was to reduce computation time. Our final answer is less than 10,000 so this works. This number can be increased, but raises the computation time)
    for num in range(1, 10000):
        #sees if the number is even a factor
        if (600851475143 % num == 0):
            prime = True
            #sees if the number is prime
            for numm in range(1,num):
                if (num % numm == 0 and numm != 1 and numm != num):
                    prime = False
            #if it is prime, adds it to the list of primes
            if (prime == True):
                primes.append(num)
                print(num)
    #selects and prints the most recent (so the largest) prime
    primee = str(primes[-1])
    print("\nThe largest prime factor of the number 600851475143 is " + primee)

#problem 4
elif (Problem == '4'):

    #reads prompt of problem
    print("Find the largest palindrome made from the product of two 3-digit numbers\n")

    #getting some variables ready 
    num1 = 100
    num2 = 100
    palindromic = 0
    
    #runs through all the 3 digit numbers for variable 1
    while (num1 != 1000):
        #runs through all the 3 digit numbers for variable 2
        while (num2 != 1000):
            #multiplies them together
            value = num1 * num2
            #checks if the product is palindromic
            if str(value) == (str(value))[::-1]:
                #checks if the palindrome is the highest so far
                if palindromic < value:
                    #if so, saves the values to print later
                    palindromic = value
                    m1 = str(num1)
                    m2 = str(num2)
            #cycles to next number
            num2 += 1
        num2 = 100
        num1 += 1

    #prints out result
    val = str(value)
    print("The largest palindrome made from the product of two 3-digit numbers is " + val + "\n" + m1 + " * "  + m2)

#problem 5
elif (Problem == '5'):

    #reads prompt of problem
    print ("What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?\n(takes a bit to load)\n")

    #num starts at 1, goes up one at a time
    num = 1

    #loops until break
    while 1==1:
        #goes through denominators 1 through 20, making sure they all are divisible evenly
        if num % 2 == 0:
            if num % 3 == 0:
                if num % 4 == 0:
                    if num % 5 == 0:
                        if num % 6 == 0:
                            if num % 7 == 0:
                                if num % 8 == 0:
                                    if num % 9 == 0:
                                        if num % 10 == 0:
                                            if num % 11 == 0:
                                                if num % 12 == 0:
                                                    if num % 13 == 0:
                                                        if num % 14 == 0:
                                                            if num % 15 == 0:
                                                                if num % 16 == 0:
                                                                    if num % 17 == 0:
                                                                        if num % 18 == 0:
                                                                            if num % 19 == 0:
                                                                                if num % 20 == 0:
                                                                                    #prints out result
                                                                                    nu = str(num)
                                                                                    print("the smallest positive number that is evenly divisible by all of the numbers from 1 to 20 is " + nu)
                                                                                    #breaks loop
                                                                                    break
        #cycles to next number                                                                        
        num += 1

#problem 6
elif (Problem == '6'):  

    #reads prompt of problem
    print("Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.\n")

    #resets variables
    num = 1
    current = 0

    #running through and adding up all the squares
    while (num != 101):
        current += num ** 2
        num += 1
    #saving this value
    top = current

    #resets variables
    num = 1
    current = 0

    #running through and adding up all the numbers
    while (num != 101):
        current += num
        num += 1
    #squares result
    bottom = current ** 2

    #calculates the answer
    diff = bottom - top

    #converts numbers to strings for print statement
    diff = str(diff)
    top = str(top)
    bottom = str(bottom)
    
    #prints out result
    print("The difference between the sum of the squares of the first one hundred natural numbers and the square of the sum is " + diff + "\n" + bottom + " - " + top + " = " + diff)


#problem failed to enter
else:
    print("Error: You didn't input a problem correctly")
